# Generated by Django 2.1.5 on 2019-06-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businesscategory', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='', max_length=30)),
                ('businesscatid', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Gotra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gotraname', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueuserid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('dob', models.CharField(max_length=10)),
                ('village', models.CharField(max_length=20)),
                ('businesscat', models.CharField(max_length=20)),
                ('businesstype', models.CharField(max_length=20)),
                ('subsurname', models.CharField(max_length=20)),
                ('activestatus', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Villages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villagename', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
